### ISSUE TITLE
/feeds page super slow

### ISSUE THREAD

**Issue by bitboxer** [stringer-rss/stringer#1060]
I am using stringer for a loong time now, and the database is rather full 🫣. Which leads to the problem that the list of feeds page (`/feeds`) is really slow. I am assuming that it's doing a super slow join to show the unread stories per feed or something like that?

**Comment by mockdeep** [comment]
Hmm, I hadn't noticed that before, but you're right, the page does take a little while to load. It looks like it's doing a bunch of "Exists?" queries to see which feeds have stories. I'll take a deeper look and see what makes sense there. We could preload the stories, but that's a lot of data to load to just determine if there are any stories.

**Comment by bitboxer** [comment]
Another way would be to put an unread_count column to the feeds? But that would mean adding logic to a couple of places, hm?

**Comment by mockdeep** [comment]
@bitboxer I don't think I've ever been able to keep a custom counter properly up to date. It may come to it, but since this is just on the one page, I'll see if I can't come up with a good query for it.

**Comment by mockdeep** [comment]
@bitboxer can you try the latest `main`? It's much faster on my instance.

**Comment by bitboxer** [comment]
Oh wow, now I finally managed to get it working and it's super fast :heart: . Thanks for this. 

Also, thanks for all your updates. Haven't updated in 6 months or so 😓 . You changed a lot. I like it.
