### ISSUE TITLE
Migration 20230223231930_add_username_to_users.rb buggy

### ISSUE THREAD

**Issue by bitboxer** [stringer-rss/stringer#1062]
I just tried to update my version of stringer, but sadly the migration `20230223231930_add_username_to_users.rb` fails because of:

```
Caused by:
NoMethodError: undefined method `sql_type' for nil:NilClass

          @case_insensitive_cache[column.sql_type] ||= begin

```

I assume it's because it adds a column and then tries to act on it. The user table schema is already loaded and those changes are not added.

**Comment by bitboxer** [comment]
A better version might be

```ruby
execute("update users set username='stringer' where username is null")
```

**Comment by mockdeep** [comment]
@bitboxer can you give the latest `main` a try? I made an update to the migration that should hopefully get you past it. Unfortunately, I was unable to reproduce the issue myself, so it's a bit of a guess.

Thanks for your persistence with this!

**Comment by bitboxer** [comment]
Looks like it worked. To re-create it yourself: do all migrations before this one, add a user to the database, continue the migrations.

I fixed it with the sql statement on my live deploy ;) .
