### ISSUE TITLE
disable sign up

### ISSUE THREAD

**Issue by bitboxer** [stringer-rss/stringer#1063]
It's great that stringer now has a multi user system, but I would love to have the ability to disable sign up for new users on my private instance :)

**Comment by mockdeep** [comment]
@bitboxer I considered adding a single-user configuration, but it seemed to me like it was pretty low risk for somebody to find your instance and sign up without you providing them a link. Is there a particular concern I'm missing? I suppose there is an off chance of bots crawling the web and signing up with spam accounts.

**Comment by bitboxer** [comment]
I once had a thing running just for me that had an open sign up. Somehow google found it...no idea how, and then people started using it. I only noticed after I got a "disk full" email. Sadly it was too late. I could not log in to that machine any more because the disk was filled to the max. But in the OS Snapshot from a week earlier, I saw nearly a thousand users 😱.

**Comment by mockdeep** [comment]
That's a pretty compelling case! I'll look into it.

**Comment by mockdeep** [comment]
@bitboxer I've added a setting so you can enable or disable user signups at your whim. It should default to disabled.

**Comment by bitboxer** [comment]
Thanks!
