### ISSUE TITLE
Fix Stringer repo Swanson link

### ISSUE THREAD

**Issue by hozza** [stringer-rss/stringer#1119]
Hey, 

_I'm just catching up with some FOSS work._ It looks like there's still a rouge link to an old repo as mentioned in https://github.com/stringer-rss/stringer/issues/1051 

I think only the repo owner can change this link?

P.S. Can we also get a repo logo?

![Screenshot from 2023-11-09 22-08-00](https://github.com/stringer-rss/stringer/assets/10520514/1c09287f-af02-45bb-b767-3ff5d379d9b0)

**Comment by mockdeep** [comment]
@hozza thanks for pointing this out. I've removed the link, since it just redirects back to this repo.
