### ISSUE TITLE
 "Feed Url" label overlaps input on the add feed screen

### ISSUE THREAD

**Issue by masukomi** [stringer-rss/stringer#1213]
see screenshot.

![CleanShot 2024-07-19 at 22 41 49@2x](https://github.com/user-attachments/assets/1026016b-0d3a-4bd3-b847-14d4f9f47ae3)

it looks ok before you try putting any content in it

![CleanShot 2024-07-19 at 22 43 46@2x](https://github.com/user-attachments/assets/6216dfe2-97c3-45a0-b21a-4cec77f6133c)

I sanity checked that this wasn't just a large font size issue. It's not. 

The short width of the box is controlled by this css: 

```
.setup .control-group input {
  width: 210px;
}
```

which, in addition to not being wide enough, is problematic in that it is defined as i fixed pixel size and thus doesn't expand with the size of a user's font setting. Should be switched to `rem` instead of `px` 

the problem with the "Feed URL" text is caused by this CSS

```
.setup .field-label {
  display: block;
  color: #BFC9CA;
  position: absolute;
  left: 13px;
  top: 10px;
  -webkit-transition: 0.25s;
  -moz-transition: 0.25s;
  -o-transition: 0.25s;
  transition: 0.25s;
}
```
This is using an absolute pixel based positioning (again a problem as font sizes - and thus line height- grow).  It's interacting negatively with the input which has _NO_ absolute positioning. The small height forces it to be over (or under) the input. if you remove the `top: 10px` it drops down to below the input which makes sense given the HTML that's creating these 2 elements and it looks like this.

![CleanShot 2024-07-19 at 22 52 33@2x](https://github.com/user-attachments/assets/66a17a14-27c8-4e3d-8fa4-aebf43e8a1f5)

Given the `top: 10px` I'm unsure if it's supposed to be above or below the input. 

(tested using Firefox)

**Comment by mockdeep** [comment]
@masukomi I think the label should be moved above the field. They appear to have been designed to be inside the field, but I may have broken it with other updates. Would you be up for making a PR?

**Comment by giovapanasiti** [comment]
@mockdeep fixed it here: https://github.com/stringer-rss/stringer/pull/1229
