### ISSUE TITLE
Enable multiple user accounts?

### ISSUE THREAD

**Issue by jiehanzheng** [stringer-rss/stringer#185]
Since Stringer already has a users table, I suppose it wouldn't be hard to add multiple user capabilities?

Google Reader is shutting down really soon, it would be nice if we can set up one Stringer instance and share it with a few friends instead of creating dedicated instances for everyone who wants to use it.

Maybe this is against Stringer's philosophy, but...yeah...I think this is a nice feature to have.

**Comment by ch3n2k** [comment]
+1

I want to install one instance of stringer for all my family.

**Comment by bitboxer** [comment]
This was now implemented by @mockdeep

**Comment by mockdeep** [comment]
This is available now. You should see an admin settings link at the bottom of the page. There you can enable user signups.
