### ISSUE TITLE
How to show the app?

### ISSUE THREAD

**Issue by tnguyen14** [stringer-rss/stringer#187]
I've followed the directions from VPS.md to set up stringer on my VPS.

Everything runs smoothly, however, when I go to the URL that points to this directory, I got the directory listing instead of the app. See image attached.
![screen shot 2013-06-05 at 12 31 51 pm](https://f.cloud.github.com/assets/1652595/613258/90359130-cdfd-11e2-8b54-eb516723b031.png)
Maybe I'm missing something fundamental here, but how can I show this app?

**Comment by duenni** [comment]
@jiehanzheng 

Could you please provide your systemd service file?
Do you also have a nginx config for stringer?

I'm trying to get this working on a VPS and just "autostart" stringer when the server boots up...
Thanks in advance!
