### ISSUE TITLE
Layout on small screens

### ISSUE THREAD

**Issue by duenni** [stringer-rss/stringer#464]
Hi,

after updating stringer to the latest commit (was on a really old one) I discovered that the layout is broken on my phone and looks like this:
![img_3961](https://user-images.githubusercontent.com/4258185/31296345-3eeee9ea-aae2-11e7-892b-ca5774ad3b58.PNG)

Any idea?

**Comment by gabrielpoca** [comment]
Hi @duenni what happened before? Was the font-size smaller on mobile devices?

**Comment by duenni** [comment]
Well, I don't know exactly. There was also the iOS 11 update, some fonts were changed there I think.
