### ISSUE TITLE
Trouble with HTTPS

### ISSUE THREAD

**Issue by gatewayshuffle** [stringer-rss/stringer#485]
First of all, thank you for making this, it looks awesome. 

However, I cannot get this to work with the following scenarios:

#### On heroku w/ custom domain and HTTPS enabled
Error:
```
Secure Connection Failed

An error occurred during a connection to news.domain.com. Peer reports it experienced an internal error. Error code: SSL_ERROR_INTERNAL_ERROR_ALERT
```
I cannot find any logging info in the app via cli. Log dir is empty.

#### On Docker with nginx-proxy and letsencrypt
Error:
```no live upstreams while connecting to upstream```

I used the docker-compose.yml from the repo and added the following under environment variables
* VIRTUAL_HOST=news.mydomain.com
* LETSENCRYPT_HOST=news.mydomain.com
* LETSENCRYPT_EMAIL=my@email.com

I also tried
* VIRTUAL_PORT=8080
* removing "ports:" and adding "expose: - 8080" 

I don't see anything in "$ env" that looks like it needs to be modified. Any help appreciated.

**Comment by gabrielpoca** [comment]
Hey @gatewayshuffle . Did you managed to make it work? I'm available to help now. I'm not sure about the Heroku one, I can try deploying it myself, but it usually works but just clicking the "deploy to heroku" button. On the docker side, what reverse proxy did you put in front of it?

**Comment by andrenho** [comment]
Just following up on this issue. I'm having this as well. I'm running the application as a docker container.

For example, one RSS I'm trying to load in the application is https://blog.codinghorror.com/rss/. If log into the stringer container (that I obtained from hub.docker.com) and curl this URL, I get the following response:

```
$ curl -v https://blog.codinghorror.com/rss/
* Hostname was NOT found in DNS cache
*   Trying 151.101.3.7...
* Connected to blog.codinghorror.com (151.101.3.7) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* 
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: certificate has expired
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I tried a few things, such as updating ca-certificates in the container, but without any luck.

Just for comparison, here's the response I get from curl when running from a regular computer:

```
curl -v -o /dev/null https://blog.codinghorror.com/rss/
* Connected to blog.codinghorror.com (2a04:4e42::775) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4033 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=blog.codinghorror.com
*  start date: Nov 23 14:18:49 2021 GMT
*  expire date: Feb 21 14:18:48 2022 GMT
*  subjectAltName: host "blog.codinghorror.com" matched cert's "blog.codinghorror.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* } [5 bytes data]
* Using Stream ID: 1 (easy handle 0x562ffdcc8910)
} [5 bytes data]
> GET /rss/ HTTP/2
> Host: blog.codinghorror.com
> user-agent: curl/7.80.0
> accept: */*
>
{ [5 bytes data]
< HTTP/2 200
< server: openresty
< content-type: text/xml; charset=utf-8
< status: 200 OK
< x-request-id: 59181f100efd64648742af89d6cfb9c8
< etag: W/"361e1-DaufgBTMsBzYwvfqyTDsl9iqORM"
< ghost-cache: HIT
< cache-control: public, max-age=0
< ghost-age: 0
< x-request-id: c3d3affbe4356e295fbd2a0689220877
< via: 1.1 varnish, 1.1 varnish
< accept-ranges: bytes
< date: Wed, 12 Jan 2022 12:24:36 GMT
< age: 140665
< x-served-by: cache-ams12769-AMS, cache-cgh11160-CGH
< x-cache: HIT, HIT
< x-cache-hits: 1, 1
< x-timer: S1641990276.305494,VS0,VE1
< vary: Accept-Encoding, Cookie
< ghost-fastly: true
< content-length: 221665
<
{ [980 bytes data]
100  216k  100  216k    0     0  1803k      0 --:--:-- --:--:-- --:--:-- 1819k
* Connection #0 to host blog.codinghorror.com left intact
```

So it seems like something is wrong with the docker container, and not the application.

**Comment by andrenho** [comment]
It doesn't seem like the certificate file is configured correctly in the system. If I force a certificate file, the call is successful:

    curl --cacert /etc/ssl/certs/cacert.pem https://blog.codinghorror.com/rss/

**Comment by mockdeep** [comment]
Hi @andrenho, thanks for digging into this. Can you try the branch `rf-ruby_up`? I [updated the Ruby image](https://github.com/stringer-rss/stringer/pull/596) and I believe that also fixes the certificate issues. I've pushed up a new image to `mockdeep/stringer`.

**Comment by mockdeep** [comment]
Actually, my changes are on `main` now, so you can try the latest version there.

**Comment by andrenho** [comment]
I tested using `mockdeep/stringer`, it is working now! Thank you!

Please let me know when you update the main image on docker hub.

**Comment by mockdeep** [comment]
@andrenho great! Until further notice, `mockdeep/stringer` is going to be the official image, so please use that.
