### ISSUE TITLE
add compatibility to raspberry pi

### ISSUE THREAD

**Issue by tommypeps** [stringer-rss/stringer#486]
Hi,
I'm trying to install stringer via dockers, Is possible add compatibility?

**Comment by Koronen** [comment]
Hi @tommypeps! It would be great if you could provide us with a bit more context here, to make it easier for us to help you. What steps have you taken so far? Are you following our ["Stringer on Docker" guide](https://github.com/swanson/stringer/blob/master/docs/docker.md)? What specific steps are breaking for you? What if any error messages are you seeing? It's possible there might be issues with Docker support on Raspberry Pi in general, as opposed to with the Stringer project specifically.

**Comment by tommypeps** [comment]
- [x] I read all documentation to install Stringer
- [x] I know the compatibility of Stringer with dockers
- [ ] I would add Stringer compatibility with Arm32v7

Hi @Koronen,

I'm installing String via Dockers with the command:
`docker network create --driver bridge stringer`

`docker run --detach \
    --name stringer-postgres \
    --restart always \
    --volume /srv/stringer/data:/var/lib/postgresql/data \
    --net stringer \
    -e POSTGRES_PASSWORD=myPassword \
    -e POSTGRES_DB=stringer \
    postgres:9.5-alpine`

finally:
`docker run --detach \
    --name stringer \
    --net stringer \
    --restart always \
    -e PORT=8080 \
    -e DATABASE_URL=postgres://postgres:myPassword@stringer-postgres/stringer \
    -e SECRET_TOKEN=$(openssl rand -hex 20) \
    -e FETCH_FEEDS_CRON="*/5 * * * *" \ # optional
    -e CLEANUP_CRON="0 0 * * *" \ # optional
    -p 127.0.0.1:8080:8080 \
    mdswanson/stringer`

but I had the following error from the logs from container stringer:

`standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error`

I make some investigation and the reason's the image dockers need architecture match

You can see more information [here](https://github.com/docker-library/official-images#architectures-other-than-amd64)

It seems someone found the [solution](https://www.ecliptik.com/Cross-Building-and-Running-Multi-Arch-Docker-Images/)

Can you are add compatibility  with arm32v7 ?

**Comment by JoseThen** [comment]
Any word on this? I tried my hand at building an ARMimage but was still met with the same `standard_init_linux.go` issues

**Comment by mockdeep** [comment]
I haven't the faintest idea of how to go about fixing this issue. It sounds like maybe the architecture of the Ruby docker image is incompatible with Raspberry PI/ARM. Looking at [the Ruby image](https://hub.docker.com/_/ruby/), it looks like it does support ARM architecture, but I'm not sure if there's a flag that needs to be set to make it work. Looking at [this issue](https://github.com/docker-library/ruby/issues/308) and [this one](https://github.com/docker-library/ruby/pull/309), maybe this will work with the latest Ruby version. @JoseThen, @tommypeps have you tried the latest Stringer release?

**Comment by JoseThen** [comment]
Not yet but I will try my hand tomorrow see how far I can get.

**Comment by guidopetri** [comment]
@tommypeps , @JoseThen : As of commit SHA 21206e70ab95d7d721e7240009cd37831cea2763, we should have compatibility with arm64. Were you looking for 32-bit ARM specifically?

**Comment by JoseThen** [comment]
> @tommypeps , @JoseThen : As of commit SHA [21206e7](https://github.com/stringer-rss/stringer/commit/21206e70ab95d7d721e7240009cd37831cea2763), we should have compatibility with arm64 (and this should be reflected on [Dockerhub](https://hub.docker.com/layers/stringerrss/stringer/latest/images/sha256-6b16693116fd1f29ec6d3c2bc6fbb3aebf77ec507e2250330a9750c580e61a2f?context=explore)). Were you looking for 32-bit ARM specifically?

I think at this point I would be looking for `64-bit ARM`.

**Comment by guidopetri** [comment]
Cool, then you should be good to pull from the `latest` tag on dockerhub.
