### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by m0nhawk** [stringer-rss/stringer#523]
The Docker image [here](https://hub.docker.com/r/mdswanson/stringer) seems be outdated, comparing to the `master` branch.

Any chance to update it? Seems like auto-build is not working as expected (from #458).

**Comment by siddjellali** [comment]
Up !

**Comment by mockdeep** [comment]
PRs welcome! I'm not sure when I'll get a chance to dig into the docker setup.

**Comment by mockdeep** [comment]
Hey @m0nhawk we've made a bunch of updates to the [docker setup](https://github.com/stringer-rss/stringer/blob/main/docs/Docker.md). Feel free to open a new issue if it's still not working for you.
