### ISSUE TITLE
Adding feed : booted out to login screen

### ISSUE THREAD

**Issue by timconsidine** [stringer-rss/stringer#578]
Using self-installed docker-compose version of stringer
Site loads and I can login after initial password submission
But when I add a feed, it just returns to me to the login screen
Logging back in, the feed has not been added
Tried safari and chrome and vivaldi/brave
Any thoughts on resolving?
I see this was an old issue but it seems to be still current

**Comment by timconsidine** [comment]
Seems it may be a docker config issue :
`recv() failed (104: Connection reset by peer) while reading response header from upstream`

**Comment by timconsidine** [comment]
Alternatively the /feeds/new page gives a message Javascript is needed (but presumably not loaded)
Browser settings permit Javascript though

**Comment by neunenak** [comment]
I'm seeing this issue myself when I try to import feeds.

**Comment by mockdeep** [comment]
Apologies to all for this. I don't think I'll have the time to look into it any time soon, but if somebody wants to submit a PR, I'll happily look it over.

**Comment by mockdeep** [comment]
We've made a bunch of updates both to the docker image and the app, so I believe this should be resolved now. Can you give it another go with the latest version and let us know if there are still issues?
