### ISSUE TITLE
Travis CI not enabled?

### ISSUE THREAD

**Issue by PeterDaveHello** [stringer-rss/stringer#582]
Though there is a [.travis.yml](https://github.com/stringer-rss/stringer/blob/master/.travis.yml), but doesn't look like it's available on Travis CI: https://app.travis-ci.com/github/stringer-rss/stringer, and https://travis-ci.org/swanson/stringer is ceased, the last build on it was 7 months ago, might because the merge of travis-ci.com & travis-ci.org, and the new service plans, would need to enable it again.

**Comment by mockdeep** [comment]
@PeterDaveHello yeah, I think we probably want to transition this to either Github Actions or CircleCI. I'd prefer CircleCI since they have a better UI, especially for debugging builds.

**Comment by mockdeep** [comment]
@PeterDaveHello I've [set Stringer up on CircleCI](https://github.com/stringer-rss/stringer/pull/594).
