### ISSUE TITLE
"An unhandled lowlevel error occurred. The application logs may have details."

### ISSUE THREAD

**Issue by dimisjim** [stringer-rss/stringer#653]
The error mentioned in the title appears when I try to access the web GUI

In the docker logs, this happens at that time:

```
2022-10-20 15:24:39,253 DEBG 'puma' stdout output:
2022-10-20 15:24:39 +0000 Rack app ("GET /" - (172.22.0.1)): #<ArgumentError: key must be 32 bytes>

2022-10-20 15:24:39,351 DEBG 'puma' stdout output:
2022-10-20 15:24:39 +0000 Rack app ("GET /favicon.ico" - (172.22.0.1)): #<ArgumentError: key must be 32 bytes>
```

Any idea what might be wrong?

Just cloned `master` and ran `docker compose up -d`, nothing special

**Comment by mockdeep** [comment]
@dimisjim you will need to update the `SECRET_TOKEN` in the `environment:` section to be a 32 character string. I believe you can generate one via `openssl rand -hex 32`. I'm not super familiar with Docker, so if you've got advice on how to make this easier, I'm all ears.

**Comment by dperson** [comment]
I've had the same errors on heroku since the 2022-09-26 Bundler Dependency merge, and have had to roll back to the prior version.

https://github.com/stringer-rss/stringer/issues/653#issuecomment-1285842338 from you @mockdeep didn't resolve it...

**Comment by mockdeep** [comment]
@dperson thanks for following up. I was able to deploy a new instance the other day. I believe I saw a similar error, but was able to resolve it by setting a key that was the proper length. It was on Heroku without docker, so not sure how that might differ. When I run `openssl rand -hex 32` it actually gives me a 64 byte string. Could you try instead `openssl rand -hex 16`? It might be that it requires *exactly* 32 bytes.

**Comment by dperson** [comment]
I tried both `openssl rand -hex 16`, `openssl rand -hex 32`, `ruby -rsecurerandom -e 'p SecureRandom.hex(32)'`, `ruby -rsecurerandom -e 'p SecureRandom.hex(16)'`, and even `ruby -rsecurerandom -e 'p SecureRandom.hex(64)'`. Restarted heroku after each time I changed it. But always get the same message from the title.

**Comment by mockdeep** [comment]
@dperson hmm, I guess I'm going to have a hard time debugging this issue if I don't have a repro. Do you have a Heroku instance that has this issue that you can add me to? My profile email is the same as I use on Heroku if you can add me as a collaborator. Otherwise, maybe we can set up a time to do a screen share?

**Comment by mockdeep** [comment]
Closing this one out. If you can provide more details we can take a deeper look. I'm also always happy to set up a screen share so we can look at it together.
