### ISSUE TITLE
ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1

### ISSUE THREAD

**Issue by brotandgames** [stringer-rss/stringer#672]
When running using `docker-compose.yml` a DEPRECATION WARNING is polluting the logs:

```
2022-12-11 13:00:08,940 DEBG 'puma' stdout output:
DEPRECATION WARNING: ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.default_timezone` instead.
 (called from block (2 levels) in <top (required)> at /app/Rakefile:56)
```

**Comment by brotandgames** [comment]
Another deprecated call:

```
2022-12-11 13:00:00,781 DEBG 'cron' stderr output:
time="2022-12-11T13:00:00Z" level=info msg="Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead." channel=stderr iteration=1 job.command="cd /app && bundle exec rake fetch_feeds" job.position=0 job.schedule="*/5 * * * *"
```

**Comment by mockdeep** [comment]
@brotandgames yeah, I've been meaning to have a look at those. I think the spell checkers one can be resolved by upgrading bundler. The other one I'm not sure, but I got the impression it is inside of delayed job, so not sure we can fix it without moving off of delayed job. Do you want to have a go at fixing them?

**Comment by mockdeep** [comment]
@brotandgames these deprecations should be gone now with the latest `main`. Can you give it another try?

**Comment by brotandgames** [comment]
Works like a charm. Thank you!
