### ISSUE TITLE
None of the docker instructions are even vaguely correct

### ISSUE THREAD

**Issue by DigitalDoc** [stringer-rss/stringer#741]
Download Docker-compose.yml and in the corresponding foler run ... give it a second and visit localhost. 

Download to where?  it seems to be hyperspecific, which would be useful to know since I'm getting an error that "unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /volume1/docker/stringer/Dockerfile: no such file or directory
ERROR: Service 'web' failed to build".  There is nothing in your instructions about needing a Dockerfile folder or directory.  the YML file seems to be vastly incomplete since it calls for a secret, while offering no information about what it is, where it's used, how to create one.  Same with the password.  Also it seems to create an image with no open ports.  Perhaps it would be a good idea to offer an example on how to check to see if any step - any step - was successful.

The manual steps are just as bad, no ports are open, there's no way to access the database which may or may not be up - no one knows or can tell - there are tons of port commands without any sort of information about what the port is for, stringer, or postgres, or both?  Who knows?

**Comment by mockdeep** [comment]
@DigitalDoc I'd welcome a PR to make the docs more helpful if you get it sorted out.

**Comment by guidopetri** [comment]
@mockdeep can you assign this issue to me?

**Comment by guidopetri** [comment]
@DigitalDoc we recently updated the docker compose + documentation surrounding it. You should be able to download the `docker-compose.yml` and run `touch .env && docker compose up -d` in the same folder. If this doesn't work for you, please let me know what issues you run into + what steps you took to get there!
