### ISSUE TITLE
unknown attribute 'enclosure_url' for Story

### ISSUE THREAD

**Issue by bitboxer** [stringer-rss/stringer#848]
I used my Sunday morning to update stringer (thanks for all those updates), and I am seeing this in my logs now:

```
E, [2023-01-29T08:15:16.630326 #1422] ERROR -- : Something went wrong when parsing https://rubyonrails.org/feed.xml: unknown attribute 'enclosure_url' for Story.

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^
```

**Comment by bitboxer** [comment]
Ah, sorry..somehow the migrations failed..now that part works again.

**Comment by mockdeep** [comment]
@bitboxer thanks for checking in! I'm making a lot of changes, but I'm hoping they will be minimally disruptive, so please let me know if anything comes up. I'm not sure what the best way to make sure migrations are run is, though. If you're running on Heroku, we could add a `release` step to the `Procfile`, but not sure if other providers honor that.

**Comment by bitboxer** [comment]
I am on a self hosted instance. I have a script that does git pull, bundle, migrate and restart. Not sure what went wrong. But it’s for sure the script that is to blame 😅
