### ISSUE TITLE
new instance UI & logic issues

### ISSUE THREAD

**Issue by masukomi** [stringer-rss/stringer#853]
A collection of issues arising from setting up a new instance. Should probably be treated as a master issue with these broken down into smaller tasks as appropriate.

Note that some of these are the result of my using large fonts because of low vision needs. I'm at Font size 20, + minimum font size 18. 

Welcome aboard message contains raw html.

<img width="524" alt="CleanShot 2023-01-29 at 13 52 23@2x" src="https://user-images.githubusercontent.com/2829/215349289-4119632f-19ae-44c1-94b7-3f856c4a9708.png">

handwriting overlay isn't readable (presumably a large font issue).

<img width="520" alt="CleanShot 2023-01-29 at 13 52 41@2x" src="https://user-images.githubusercontent.com/2829/215349328-9e434ce6-6fc2-4750-902c-b9eb3140a71d.png">

when you add your first feed it says you've reached RSS Zero despite a) not having read anything and b) the goal of adding the feed presumably being to see feed content in the feed reader

<img width="643" alt="CleanShot 2023-01-29 at 13 53 25@2x" src="https://user-images.githubusercontent.com/2829/215349402-5a67c375-7662-42de-bdd1-8199991015b2.png">

clicking "view all items" tells you "you haven't read any stories". This of course directly contradicts the idea that i've reached inbox zero. Either i HAVE read everything or i haven't read anything. Both can't be true at this point. 

<img width="432" alt="CleanShot 2023-01-29 at 13 53 37@2x" src="https://user-images.githubusercontent.com/2829/215349430-356d6dd2-c390-42aa-9f3b-84f9f60c47f4.png">

clicking into the list of feeds i see this, which indicates that there are 6 unread. Again, self contradicting data. Either there ARE 6 items waiting to be read OR I've "reached RSS Zero". Can't be both. 

also note the icons overlapping the text on the right side of the row and making it unreadable. Presumably another accessibility issue related to large fonts. 

<img width="748" alt="CleanShot 2023-01-29 at 13 53 46@2x" src="https://user-images.githubusercontent.com/2829/215349450-03cbd475-ea4d-4050-a0c6-6b99c4b8b45c.png">

**Comment by mockdeep** [comment]
Thanks for the feedback! I'll see if I can get at least some of these addressed. One point I would disagree with, though:

> Either i HAVE read everything or i haven't read anything. Both can't be true at this point.

If you have 0 stories, by definition you have both read everything and not read anything. To get super technical, in set logic "By the definition of [subset](https://en.wikipedia.org/wiki/Subset), the empty set is a subset of any set A." ([source](https://en.wikipedia.org/wiki/Empty_set)) Similar to Ruby arrays:

```rb
> [].all?(&:nil?)
=> true
> [].all?(&:present?)
=> true
```

But there's probably still some room for improving the wording.

**Comment by mockdeep** [comment]
> clicking into the list of feeds i see this, which indicates that there are 6 unread. Again, self contradicting data. Either there ARE 6 items waiting to be read OR I've "reached RSS Zero". Can't be both.

Can you provide more context on this? From what I can tell, the counters on the feeds page seem to be accurate. Is it possible the feed finished refreshing while you were on the empty `/news` page? We don't dynamically update the news page when new stories have come in from a feed.

**Comment by mockdeep** [comment]
@masukomi I've made some adjustments. Can you try the latest `main`?

**Comment by masukomi** [comment]
not sure what you changed but i think you've addressed all my concerns here. Yes it says "you've reached rss zero" at the start but i think that's understandable. when you add a feed it still says zero but says check back later, so that's clear. little handwriting things worked well with the 3 items it displayed, no raw html.... yeah i think it's all good :D 

thanks.

**Comment by mockdeep** [comment]
Closing, thanks for the feedback and please open a new issue if you notice anything else!
