### ISSUE TITLE
Use http://www.localeapp.com/ to manage I18n

### ISSUE THREAD

**Issue by stefanoverna** [stringer-rss/stringer#99]
Keeping I18n in sync would be much easier with this. Also, it's free for public projects like stringer.

**Comment by Coool** [comment]
"After more than a decade of making localization easier for Ruby on Rails developers, LocaleApp was sunset on April 5, 2025."

@swanson, any replacement?

**Comment by mockdeep** [comment]
@Coool oh, wow, I didn't know we were hooked up to LocaleApp. I've been updating files directly in the repo as have [others](https://github.com/stringer-rss/stringer/pull/1297). I'm open to an alternative if you know one.

**Comment by Coool** [comment]
@mockdeep, developers mostly use [Crowdin](https://github.com/crowdin) or [Weblate](we). I personally like Weblate.
